version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    groups:
      rust-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
